
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: codeMaker
    password: codemaker

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      ddl-auto: create-drop

logging:
  level:
    sql: debug